package com.transiva.app;
import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;
public class TransAssistantTourActivity extends Activity{
    static final String PREF="trans_assistant_onboarding",KEY="done"; private TextView status;
    public static boolean isDone(Activity a){return a.getSharedPreferences(PREF,0).getBoolean(KEY,false);}
    @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(build());}
    @Override protected void onResume(){super.onResume();refresh();}
    private View build(){ScrollView sc=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(22),dp(28),dp(22),dp(28));r.setBackgroundColor(Color.parseColor("#F7FAFF"));r.addView(txt("Trans Assistant",28,true));r.addView(txt("Panduan pintar Transiva tanpa API eksternal",16,true));r.addView(txt("Trans Assistant membantu cara pemesanan, chat, panggilan, pembayaran, akun, dan fitur lain. Jawaban utama tersedia langsung di aplikasi.",14,false));r.addView(txt("Agar layar panggilan lebih lancar ketika aplikasi berada di latar belakang, aktifkan izin Tampil di atas aplikasi lain. Izin ini opsional dan bisa diubah kapan saja.",14,false));status=txt("Memeriksa izin...",14,true);r.addView(status);Button overlay=new Button(this);overlay.setText("Atur izin tampil di atas aplikasi lain");overlay.setOnClickListener(v->{if(Build.VERSION.SDK_INT>=23)startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION, Uri.parse("package:"+getPackageName())));});r.addView(overlay);Button assistant=new Button(this);assistant.setText("Coba Trans Assistant");assistant.setOnClickListener(v->startActivity(new Intent(this,TransAssistantActivity.class)));r.addView(assistant);Button done=new Button(this);done.setText("Lanjut ke Transiva");done.setOnClickListener(v->{getSharedPreferences(PREF,0).edit().putBoolean(KEY,true).apply();route();});r.addView(done);sc.addView(r);return sc;}
    private void refresh(){if(status!=null)status.setText(Build.VERSION.SDK_INT<23||Settings.canDrawOverlays(this)?"✓ Izin tampil di atas aplikasi lain aktif":"• Izin belum aktif — Anda tetap dapat melanjutkan");}
    private void route(){SessionManager s=new SessionManager(this);Intent i=s.isLoggedIn()?new Intent(this,CustomerDashboardActivity.class):new Intent(this,LoginActivity.class);i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK);startActivity(i);finish();}
    private TextView txt(String s,int z,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.parseColor("#17324D"));v.setPadding(0,dp(8),0,dp(8));if(b)v.setTypeface(null,1);return v;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
