package com.transiva.app;
import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;
public class TransAssistantActivity extends Activity{
    private LinearLayout messages; private EditText input; private TransAssistantEngine engine;
    @Override protected void onCreate(Bundle b){super.onCreate(b);engine=new TransAssistantEngine(this);TransAssistantSync.sync(this);setContentView(build());addBot("Halo, saya Trans Assistant. Saya bisa membantu cara pemesanan, chat, panggilan, pembayaran, akun, dan penggunaan fitur Transiva.","","");}
    private View build(){ LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.parseColor("#F7FAFF")); TextView bar=t("←  Trans Assistant",20,true);bar.setTextColor(Color.WHITE);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(16),dp(18),dp(16),dp(18));bar.setBackgroundColor(Color.parseColor("#075EF4"));bar.setOnClickListener(v->finish());root.addView(bar,new LinearLayout.LayoutParams(-1,-2)); ScrollView sc=new ScrollView(this);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);messages.setPadding(dp(12),dp(12),dp(12),dp(12));sc.addView(messages);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1)); LinearLayout row=new LinearLayout(this);row.setPadding(dp(10),dp(8),dp(10),dp(10));input=new EditText(this);input.setHint("Tanya Trans Assistant...");input.setSingleLine(false);input.setMaxLines(3);input.setImeOptions(EditorInfo.IME_ACTION_SEND);row.addView(input,new LinearLayout.LayoutParams(0,-2,1));Button send=new Button(this);send.setText("Kirim");send.setOnClickListener(v->send());row.addView(send);root.addView(row);return root; }
    private void send(){String q=input.getText().toString().trim();if(q.isEmpty())return;addUser(q);input.setText("");TransAssistantEngine.Reply r=engine.answer(q);addBot(r.text,r.action,r.actionLabel);}
    private void addUser(String s){TextView v=t(s,15,false);v.setTextColor(Color.WHITE);v.setBackground(Shape.round("#0B7CFF",dp(16)));v.setPadding(dp(12),dp(10),dp(12),dp(10));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.gravity=Gravity.END;lp.setMargins(dp(52),dp(6),0,dp(6));messages.addView(v,lp);}
    private void addBot(String s,String action,String label){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),dp(10),dp(12),dp(10));box.setBackground(Shape.roundStroke("#FFFFFF","#D7E5F7",dp(16),1));TextView v=t(s,15,false);v.setTextColor(Color.parseColor("#17324D"));box.addView(v);if(action!=null&&!action.isEmpty()){Button b=new Button(this);b.setText(label==null||label.isEmpty()?"Buka":label);b.setOnClickListener(x->TransAssistantActions.run(this,action));box.addView(b);}LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(6),dp(38),dp(6));messages.addView(box,lp);}
    private TextView t(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);if(bold)v.setTypeface(null,1);return v;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
