package com.transiva.app;

import android.app.Activity;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.Gravity;import android.view.View;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.text.NumberFormat;import java.util.Locale;

public class CustomerLoyaltyActivity extends Activity{
 private static final String URL="https://transiva.my.id/server/customer_loyalty.php", REDEEM="https://transiva.my.id/server/customer_loyalty_redeem.php"; private LinearLayout root; private ProgressBar loading; private JSONObject data;
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.parseColor("#075ED1"));setContentView(base());load();}
 private View base(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(Color.parseColor("#F4F7FC"));root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(36));s.addView(root);TextView h=tx("‹   Transiva Royalti",24,"#0B3A78",true);h.setOnClickListener(v->finish());root.addView(h);root.addView(tx("Reward untuk setiap perjalanan dan pesananmu",13,"#64748B",false));loading=new ProgressBar(this);LinearLayout.LayoutParams l=new LinearLayout.LayoutParams(-2,-2);l.gravity=Gravity.CENTER;l.setMargins(0,dp(30),0,0);root.addView(loading,l);return s;}
 private void load(){new Thread(()->{try{JSONObject o=request(URL,null);runOnUiThread(()->render(o));}catch(Exception e){runOnUiThread(()->error("Gagal memuat Royalti. Periksa koneksi lalu coba lagi."));}},"loyalty").start();}
 private void render(JSONObject o){loading.setVisibility(View.GONE);while(root.getChildCount()>3)root.removeViewAt(3);if(!o.optBoolean("success")){error(o.optString("message","Gagal memuat Royalti"));return;}data=o.optJSONObject("data");if(data==null)data=new JSONObject();int points=data.optInt("points"),earned=data.optInt("earned_points",points);String tier=data.optString("tier","BRONZE");
  LinearLayout hero=card("#0878F9",26);hero.addView(tx("★  "+tier+" MEMBER",14,"#DDF2FF",true));hero.addView(tx(fmt(points)+" poin",34,"#FFFFFF",true));hero.addView(tx("Poin tersedia • "+fmt(earned)+" poin lifetime",12,"#EAF4FF",false));hero.addView(tx(data.optString("next_tier_text",""),13,"#FFFFFF",true));root.addView(hero,margin(18));
  addTierTrack(earned,tier);
  LinearLayout expl=card("#FFFFFF",22);expl.addView(tx("Cara kerja Royalti",17,"#0B3A78",true));expl.addView(tx("Setiap Rp1.000 transaksi selesai = 1 poin. Tier dihitung dari poin lifetime, sehingga menukar voucher tidak menurunkan level member.",13,"#475569",false));root.addView(expl,margin(14));
  TextView title=tx("Voucher Royalti",20,"#0B3A78",true);title.setPadding(0,dp(22),0,dp(4));root.addView(title);root.addView(tx("Mulai Silver, poin dapat ditukar voucher. Semakin tinggi tier, semakin besar manfaat reward yang terbuka.",13,"#64748B",false));
  JSONArray rewards=data.optJSONArray("rewards");if(rewards==null||rewards.length()==0){root.addView(tx("Katalog voucher belum tersedia. Jalankan migrasi loyalty_upgrade.sql di server.",13,"#B45309",true),margin(12));}else for(int i=0;i<rewards.length();i++){JSONObject r=rewards.optJSONObject(i);if(r!=null)addReward(r,points);}
  JSONArray owned=data.optJSONArray("owned_vouchers");if(owned!=null&&owned.length()>0){root.addView(tx("Voucher Saya",20,"#0B3A78",true),margin(22));for(int i=0;i<owned.length();i++){JSONObject v=owned.optJSONObject(i);LinearLayout c=card("#ECFDF5",18);c.addView(tx(v.optString("title"),15,"#065F46",true));c.addView(tx(v.optString("voucher_code"),19,"#047857",true));c.addView(tx("Berlaku sampai "+v.optString("expires_at","-"),11,"#475569",false));root.addView(c,margin(10));}}
 }
 private void addTierTrack(int earned,String current){LinearLayout c=card("#FFFFFF",22);c.addView(tx("Perjalanan levelmu",17,"#0B3A78",true));String[] n={"Bronze","Silver","Gold","Diamond","Platinum"};int[] p={0,500,1500,3000,5000};LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,dp(15),0,0);for(int i=0;i<n.length;i++){LinearLayout col=new LinearLayout(this);col.setOrientation(LinearLayout.VERTICAL);col.setGravity(Gravity.CENTER);TextView dot=tx(earned>=p[i]?"●":"○",22,earned>=p[i]?"#0878F9":"#CBD5E1",true);col.addView(dot);col.addView(tx(n[i],10,"#334155",true));col.addView(tx(fmt(p[i]),9,"#94A3B8",false));row.addView(col,new LinearLayout.LayoutParams(0,-2,1));}c.addView(row);ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(5000);bar.setProgress(Math.min(5000,earned));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(7));bp.setMargins(dp(8),dp(8),dp(8),0);c.addView(bar,bp);root.addView(c,margin(14));}
 private void addReward(JSONObject r,int points){boolean unlocked=r.optBoolean("unlocked"),can=r.optBoolean("can_redeem");int cost=r.optInt("points_cost"),remaining=r.optInt("quota_remaining",-1);LinearLayout c=card("#FFFFFF",22);TextView badge=tx((unlocked?"TERBUKA":"🔒 "+r.optString("min_tier"))+"  •  "+cost+" poin",11,unlocked?"#0878F9":"#94A3B8",true);c.addView(badge);c.addView(tx(r.optString("title"),18,"#0F172A",true));c.addView(tx(r.optString("description"),13,"#475569",false));String q=remaining<0?"Kuota tersedia":"Sisa kuota: "+remaining;c.addView(tx(q+"  •  Min. order "+rupiah(r.optInt("min_order")),11,"#64748B",false));Button b=new Button(this);b.setAllCaps(false);b.setText(can?"Tukar • "+cost+" poin":(!unlocked?"Capai "+r.optString("min_tier"):(points<cost?"Poin belum cukup":"Kuota habis")));b.setEnabled(can);b.setTextColor(Color.WHITE);b.setBackground(round(can?"#0878F9":"#94A3B8",16));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(48));lp.setMargins(0,dp(12),0,0);c.addView(b,lp);b.setOnClickListener(v->confirmRedeem(r));root.addView(c,margin(12));}
 private void confirmRedeem(JSONObject r){String terms=r.optString("terms_text","Voucher mengikuti syarat dan ketentuan Transiva.");new TransivaAlertDialogBuilder(this).setTitle("Konfirmasi Penukaran").setMessage(r.optString("title")+"\n\nBiaya: "+r.optInt("points_cost")+" poin\n\nS&K:\n"+terms+"\n\nPoin akan dipotong setelah Anda mengonfirmasi.").setNegativeButton("Batal",null).setPositiveButton("Tukar Voucher",(d,w)->redeem(r.optInt("id"))).show();}
 private void redeem(int id){new Thread(()->{try{JSONObject p=new JSONObject();p.put("reward_id",id);JSONObject o=request(REDEEM,p);runOnUiThread(()->{new TransivaAlertDialogBuilder(this).setTitle(o.optBoolean("success")?"Voucher Berhasil":"Penukaran Gagal").setMessage(o.optBoolean("success")?"Kode voucher: "+o.optString("voucher_code")+"\n\nVoucher sudah masuk ke Voucher Saya.":o.optString("message","Gagal menukar voucher")).setPositiveButton("OK",(d,w)->{if(o.optBoolean("success")){loading.setVisibility(View.VISIBLE);load();}}).show();});}catch(Exception e){runOnUiThread(()->error("Koneksi gagal saat menukar voucher."));}},"redeem").start();}
 private JSONObject request(String u,JSONObject body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();CustomerApiClient.applySecurity(this,c);c.setConnectTimeout(15000);c.setReadTimeout(15000);if(body!=null){c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");try(OutputStream os=c.getOutputStream()){os.write(body.toString().getBytes(StandardCharsets.UTF_8));}}else c.setRequestMethod("GET");InputStream in=c.getResponseCode()>=400?c.getErrorStream():c.getInputStream();StringBuilder b=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String l;while((l=r.readLine())!=null)b.append(l);}return new JSONObject(b.toString());}
 private void error(String s){loading.setVisibility(View.GONE);TextView x=tx(s,14,"#B91C1C",true);root.addView(x,margin(16));}
 private LinearLayout card(String c,int r){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(18),dp(18),dp(18),dp(18));x.setBackground(round(c,r));return x;}private GradientDrawable round(String c,int r){GradientDrawable g=new GradientDrawable();g.setColor(Color.parseColor(c));g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams margin(int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(top),0,0);return p;}private TextView tx(String s,int z,String c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.parseColor(c));t.setLineSpacing(0,1.12f);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private String fmt(int n){return NumberFormat.getIntegerInstance(new Locale("id","ID")).format(n);}private String rupiah(int n){return "Rp"+fmt(n);}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
