package com.transiva.app;
import android.app.Activity; import android.graphics.*; import android.graphics.drawable.GradientDrawable; import android.os.Bundle; import android.view.*; import android.widget.*; import org.json.*; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets;
public class CustomerLoyaltyActivity extends Activity{
 static final String URL="https://transiva.my.id/server/customer_loyalty.php"; LinearLayout root; ProgressBar p;
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.parseColor("#0B7CFF"));setContentView(ui());load();}
 View ui(){ScrollView s=new ScrollView(this);s.setBackgroundColor(Color.parseColor("#F6F9FE"));root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(30));s.addView(root);TextView h=t("‹  Transiva Royalti",24,"#0B3A78",true);h.setOnClickListener(v->finish());root.addView(h);p=new ProgressBar(this);root.addView(p);return s;}
 void load(){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(URL).openConnection();CustomerApiClient.applySecurity(this,c);c.setRequestMethod("GET");StringBuilder b=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.UTF_8))){String l;while((l=r.readLine())!=null)b.append(l);}JSONObject o=new JSONObject(b.toString());runOnUiThread(()->render(o));}catch(Exception e){runOnUiThread(()->{p.setVisibility(View.GONE);root.addView(t("Gagal memuat royalti. Coba lagi saat koneksi stabil.",14,"#B91C1C",true));});}},"loyalty").start();}
 void render(JSONObject o){p.setVisibility(View.GONE);if(!o.optBoolean("success")){root.addView(t(o.optString("message","Gagal memuat royalti"),14,"#B91C1C",true));return;}JSONObject d=o.optJSONObject("data"); if(d==null)d=new JSONObject(); LinearLayout hero=box("#0B7CFF");hero.addView(t(d.optString("tier","BRONZE")+" MEMBER",14,"#DDF2FF",true));hero.addView(t(String.valueOf(d.optInt("points",0))+" poin",32,"#FFFFFF",true));hero.addView(t("Total transaksi selesai: "+d.optInt("completed_orders",0),13,"#FFFFFF",false));root.addView(hero,lp());
 LinearLayout info=box("#FFFFFF");info.addView(t("Cara mendapatkan poin",17,"#0B3A78",true));info.addView(t("Setiap Rp1.000 transaksi selesai = 1 poin. Poin dihitung server agar tidak dapat dimanipulasi dari aplikasi.",13,"#475569",false));info.addView(t("\nProgress tier berikutnya",14,"#0B3A78",true));info.addView(t(d.optString("next_tier_text","Pertahankan transaksi aktif untuk naik tier."),13,"#64748B",false));root.addView(info,lp());}
 LinearLayout box(String c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(18),dp(18),dp(18),dp(18));x.setBackground(round(c,22));return x;} LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(18),0,0);return p;} TextView t(String s,int z,String c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.parseColor(c));if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;} GradientDrawable round(String c,int r){GradientDrawable g=new GradientDrawable();g.setColor(Color.parseColor(c));g.setCornerRadius(dp(r));return g;}int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
