package com.transiva.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.text.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import java.net.*;
import java.io.*;

public class CustomerSupportActivity extends Activity {
 private final int blue=0xff147df5, ink=0xff173b65, muted=0xff66788d, bg=0xfff4f8fe;
 private LinearLayout root, history; private boolean loadingHistory=false; private EditText subject,detail; private Spinner category; private TextView send, counter; private boolean sending=false; private SharedPreferences draft;
 private int dp(float n){return (int)(getResources().getDisplayMetrics().density*n+.5f);}
 private GradientDrawable shape(int color,int radius,int stroke){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));if(stroke!=0)d.setStroke(dp(1),stroke);return d;}
 private TextView txt(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);if(bold)t.setTypeface(null,Typeface.BOLD);return t;}
 private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
 private void add(LinearLayout p,View v,int bottom){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(bottom);p.addView(v,lp);}
 private LinearLayout card(){LinearLayout l=column();l.setPadding(dp(13),dp(12),dp(13),dp(12));l.setBackground(shape(Color.WHITE,19,0xffdce7f2));return l;}
 private TextView action(String s,boolean primary){TextView t=txt(s,15,primary?Color.WHITE:blue,true);t.setGravity(Gravity.CENTER);t.setMinHeight(dp(49));t.setPadding(dp(10),dp(10),dp(10),dp(10));t.setBackground(shape(primary?blue:Color.WHITE,14,primary?0:0xffbed8f1));t.setClickable(true);return t;}
 private EditText field(String hint,int lines){EditText e=new EditText(this);e.setTextSize(14);e.setTextColor(ink);e.setHintTextColor(muted);e.setHint(hint);e.setPadding(dp(12),dp(11),dp(12),dp(11));e.setBackground(shape(0xfff8fbff,12,0xffd8e4ef));if(lines==1){e.setSingleLine(true);}else{e.setGravity(Gravity.TOP);e.setMinLines(2);e.setMaxLines(6);e.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);}return e;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(blue);getWindow().setNavigationBarColor(Color.BLACK);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);draft=getSharedPreferences("support_draft_v2",MODE_PRIVATE);
 ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);scroll.setBackgroundColor(bg);root=column();root.setPadding(dp(14),dp(10),dp(14),dp(54));scroll.addView(root);setContentView(scroll);
 LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);TextView back=txt("‹",32,blue,true);back.setGravity(Gravity.CENTER);back.setWidth(dp(40));header.addView(back);back.setOnClickListener(v->finish());TextView title=txt("Pusat Bantuan",22,ink,true);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView headset=txt("🎧",23,blue,false);header.addView(headset);add(root,header,9);
 LinearLayout intro=card();intro.setBackground(shape(0xffe9f3ff,17,0));add(intro,txt("Ada yang bisa kami bantu?",16,ink,true),4);add(intro,txt("Ceritakan kendala Anda kepada tim Transiva.",13,muted,false),5);add(intro,txt("✓ Laporan tersimpan dan ditindaklanjuti admin",11,0xff23835c,false),0);add(root,intro,12);
 add(root,txt("Buat laporan baru",17,ink,true),7);LinearLayout form=card();add(root,form,12);add(form,txt("Kategori keluhan",13,ink,true),7);category=new Spinner(this);String[] cats={"Pesanan / perjalanan","Pembayaran / saldo","Akun / login","Driver / merchant","Aplikasi / teknis","Lainnya"};ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,cats);category.setAdapter(adapter);category.setBackground(shape(0xfff8fbff,12,0xffd8e4ef));add(form,category,9);int saved=draft.getInt("category",0);category.setSelection(Math.max(0,Math.min(saved,cats.length-1)));
 add(form,txt("Judul keluhan",13,ink,true),6);subject=field("Contoh: Saldo belum masuk",1);subject.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(150)});subject.setText(draft.getString("subject",""));add(form,subject,9);add(form,txt("Detail kendala",13,ink,true),6);detail=field("Jelaskan kendala yang Anda alami...",3);detail.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(4000)});detail.setText(draft.getString("detail",""));add(form,detail,5);counter=txt("",11,muted,false);counter.setGravity(Gravity.RIGHT);add(form,counter,8);send=action("Kirim Keluhan",true);add(form,send,0);send.setOnClickListener(v->submit());TextWatcher watcher=new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){updateSend();saveDraft();}public void afterTextChanged(Editable e){}};subject.addTextChangedListener(watcher);detail.addTextChangedListener(watcher);category.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){saveDraft();}});updateSend();
 TextView wa=action("Hubungi Admin via WhatsApp   ›",false);wa.setCompoundDrawablePadding(dp(8)); android.graphics.drawable.Drawable waIcon=new android.graphics.drawable.Drawable(){android.graphics.Paint paint=new android.graphics.Paint(3); public void draw(android.graphics.Canvas c){android.graphics.Rect b=getBounds();float x=b.exactCenterX(),y=b.exactCenterY(),r=Math.min(b.width(),b.height())*.40f;paint.setColor(0xff20a566);paint.setStyle(android.graphics.Paint.Style.STROKE);paint.setStrokeWidth(dp(2));c.drawCircle(x,y,r,paint);android.graphics.Path tail=new android.graphics.Path();tail.moveTo(x-r*.65f,y+r*.65f);tail.lineTo(x-r*.94f,y+r*1.08f);tail.lineTo(x-r*.12f,y+r*.85f);c.drawPath(tail,paint);paint.setStyle(android.graphics.Paint.Style.FILL);paint.setTextSize(dp(14));paint.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("☎",x-dp(6),y+dp(5),paint);}public void setAlpha(int a){}public void setColorFilter(android.graphics.ColorFilter f){}public int getOpacity(){return android.graphics.PixelFormat.TRANSLUCENT;}};waIcon.setBounds(0,0,dp(25),dp(25));wa.setCompoundDrawables(waIcon,null,null,null);add(root,wa,13);wa.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/6282393633393?text="+Uri.encode("Halo Admin Transiva, saya membutuhkan bantuan."))));}catch(Exception e){Toast.makeText(this,"Tidak dapat membuka WhatsApp",Toast.LENGTH_SHORT).show();}});
 LinearLayout hr=new LinearLayout(this);hr.setGravity(Gravity.CENTER_VERTICAL);TextView h=txt("Riwayat keluhan",17,ink,true);hr.addView(h,new LinearLayout.LayoutParams(0,-2,1));TextView refresh=txt("↻ Segarkan",13,blue,true);hr.addView(refresh);refresh.setOnClickListener(v->load());add(root,hr,10);history=column();add(root,history,0);load(); }
 private void saveDraft(){if(subject==null||detail==null||category==null)return;draft.edit().putString("subject",subject.getText().toString()).putString("detail",detail.getText().toString()).putInt("category",category.getSelectedItemPosition()).apply();}
 private void updateSend(){if(send==null)return;boolean valid=subject.getText().toString().trim().length()>=5&&detail.getText().toString().trim().length()>=15;send.setEnabled(valid&&!sending);send.setAlpha(valid&&!sending?1f:.48f);counter.setText(detail.length()+" / 4000 karakter");}
 private void submit(){if(sending)return;String a=subject.getText().toString().trim(),d=detail.getText().toString().trim();if(a.length()<5){subject.setError("Minimal 5 karakter");subject.requestFocus();return;}if(d.length()<15){detail.setError("Minimal 15 karakter");detail.requestFocus();return;}sending=true;send.setText("Mengirim laporan...");updateSend();try{JSONObject body=new JSONObject();body.put("category",category.getSelectedItem().toString());body.put("subject",a);body.put("detail",d);request("POST",body,result->{sending=false;send.setText("Kirim Keluhan");if(result.optBoolean("success")){draft.edit().clear().apply();subject.setText("");detail.setText("");Toast.makeText(this,"Laporan berhasil dikirim",Toast.LENGTH_SHORT).show();load();}else Toast.makeText(this,result.optString("message","Gagal mengirim laporan. Coba lagi."),Toast.LENGTH_LONG).show();updateSend();});}catch(Exception e){sending=false;send.setText("Kirim Keluhan");updateSend();Toast.makeText(this,"Gagal menyiapkan laporan",Toast.LENGTH_SHORT).show();}}
 private interface Result{void done(JSONObject data);}
 private void request(String method,JSONObject payload,Result callback){TransivaNetworkExecutor.execute(()->{JSONObject result=new JSONObject();HttpURLConnection c=null;try{c=CustomerApiClient.open(this,ApiConfig.server("customer_support_native.php"));c.setConnectTimeout(12000);c.setReadTimeout(16000);c.setRequestProperty("Accept","application/json");if("POST".equals(method)){c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");try(OutputStream o=c.getOutputStream()){o.write(payload.toString().getBytes("UTF-8"));}}InputStream in=(c.getResponseCode()<400?c.getInputStream():c.getErrorStream());if(in==null)throw new IOException("Empty response");try(InputStream stream=in;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buf=new byte[4096];int n;while((n=stream.read(buf))!=-1)out.write(buf,0,n);result=new JSONObject(out.toString("UTF-8"));}}catch(Exception e){try{result.put("message","Koneksi bermasalah. Silakan coba lagi.");}catch(Exception ignored){}}finally{if(c!=null)c.disconnect();}JSONObject r=result;runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())callback.done(r);});});}
 private String status(String raw){switch(raw.toLowerCase(java.util.Locale.ROOT)){case "open":case "pending":return "Menunggu";case "in_progress":case "processing":return "Diproses";case "answered":case "replied":return "Dijawab Admin";case "resolved":case "closed":return "Selesai";default:return raw.isEmpty()?"Menunggu":raw;}}
 private int statusColor(String raw){String s=status(raw);return s.equals("Selesai")?0xff21845c:s.equals("Diproses")?0xffae7517:s.equals("Dijawab Admin")?blue:muted;}
 private void load(){if(loadingHistory)return;loadingHistory=true;history.removeAllViews();add(history,txt("Memuat riwayat...",13,muted,false),0);request("GET",null,r->{loadingHistory=false;history.removeAllViews();if(!r.optBoolean("success")){add(history,txt(r.optString("message","Riwayat belum tersedia"),13,muted,false),0);return;}JSONArray rows=r.optJSONArray("tickets");if(rows==null||rows.length()==0){add(history,txt("Belum ada keluhan. Laporan Anda akan muncul di sini.",13,muted,false),0);return;}for(int i=0;i<rows.length();i++){JSONObject t=rows.optJSONObject(i);if(t==null)continue;LinearLayout item=card();add(history,item,9);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView id=txt("#TK-"+String.format(java.util.Locale.ROOT,"%04d",t.optInt("id")),13,ink,true);top.addView(id,new LinearLayout.LayoutParams(0,-2,1));String raw=t.optString("status","");TextView badge=txt(status(raw),12,statusColor(raw),true);badge.setPadding(dp(9),dp(5),dp(9),dp(5));badge.setBackground(shape(status(raw).equals("Selesai")?0xffe4f7ed:status(raw).equals("Diproses")?0xfffff3d9:status(raw).equals("Dijawab Admin")?0xffe5f1ff:0xffeff3f8,10,0));top.addView(badge);add(item,top,9);add(item,txt(t.optString("subject","Keluhan"),15,ink,true),6);add(item,txt(t.optString("created_at","")+"     Detail ›",12,muted,false),0);item.setClickable(true);item.setOnClickListener(v->showTicket(t));}});}
 private void showTicket(JSONObject t){LinearLayout body=column();body.setPadding(dp(20),dp(8),dp(20),0);add(body,txt("Kategori: "+t.optString("category","-"),13,muted,false),10);add(body,txt(t.optString("subject","Keluhan"),17,ink,true),8);add(body,txt("Dikirim: "+t.optString("created_at","-"),12,muted,false),10);add(body,txt("Keluhan Anda",13,blue,true),5);add(body,txt(t.optString("detail","-"),14,ink,false),16);add(body,txt("Respons admin",13,blue,true),5);String reply=t.optString("admin_reply","");add(body,txt(reply.trim().isEmpty()?"Belum ada balasan admin.":reply,14,ink,false),dp(4));ScrollView ticketScroll=new ScrollView(this);ticketScroll.setFillViewport(false);ticketScroll.addView(body);new AlertDialog.Builder(this).setTitle("Tiket #"+t.optInt("id")+" • "+status(t.optString("status",""))).setView(ticketScroll).setPositiveButton("Tutup",(d,w)->{}).setNeutralButton("WhatsApp",(d,w)->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/6282393633393?text="+Uri.encode("Halo Admin Transiva, saya ingin menanyakan tiket #"+t.optInt("id")))));}catch(Exception e){Toast.makeText(this,"Tidak dapat membuka WhatsApp",Toast.LENGTH_SHORT).show();}}).show();}
}
