package com.transiva.app;

import android.app.Activity;import android.content.Intent;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.Bundle;import android.view.Gravity;import android.view.View;import android.widget.*;import java.util.List;

public class SafetyCenterActivity extends Activity implements UnifiedLiveOrderCenter.Listener {
    private LinearLayout activeBox; private TextView activeInfo;
    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.parseColor("#0B7CFF"));setContentView(screen());CustomerAppSettings.apply(this);UnifiedLiveOrderCenter.addListener(this);UnifiedLiveOrderCenter.refresh(this,null);}
    @Override protected void onDestroy(){UnifiedLiveOrderCenter.removeListener(this);super.onDestroy();}
    private ScrollView screen(){ScrollView s=new ScrollView(this);s.setBackgroundColor(Color.parseColor("#F6F9FE"));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(30));s.addView(r);TextView back=t("‹  Safety Center 2.0",24,"#0B3A78",true);back.setOnClickListener(v->finish());r.addView(back);TextView hero=t("Perjalanan lebih aman, bantuan lebih cepat",22,"#0B3A78",true);hero.setPadding(0,dp(24),0,dp(6));r.addView(hero);r.addView(t("Safety Center membaca perjalanan aktif dari server agar informasi yang dibagikan tetap relevan.",13,"#64748B",false));
        activeBox=box();activeInfo=t("Memeriksa perjalanan aktif…",13,"#475569",false);activeBox.addView(t("Perjalanan aktif",17,"#0B3A78",true));activeBox.addView(activeInfo);r.addView(activeBox,lp());
        r.addView(card("🆘  Panggilan Darurat 112","Buka dialer layanan darurat. Ketersediaan mengikuti wilayah setempat.",()->startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:112")))),lp());
        r.addView(card("📍  Bagikan Perjalanan Aktif","Bagikan layanan, status, titik jemput, dan tujuan kepada orang tepercaya.",this::shareActiveTrip),lp());
        r.addView(card("🚗  Cek Driver & Kendaraan","Buka Live Order Center untuk mencocokkan order aktif sebelum perjalanan.",()->startActivity(new Intent(this,LiveOrderCenterActivity.class))),lp());
        r.addView(card("🔐  Lindungi Transiva Pay","Aktifkan biometrik dan jangan pernah membagikan PIN atau OTP.",()->startActivity(new Intent(this,CustomerSettingsActivity.class))),lp());
        LinearLayout tips=box();tips.addView(t("Tips keselamatan",17,"#0B3A78",true));tips.addView(t("• Pastikan identitas driver sesuai aplikasi.\n• Jangan berikan OTP/PIN kepada siapa pun.\n• Bagikan perjalanan jika merasa perlu.\n• Jika situasi tidak aman, turun di tempat ramai dan hubungi bantuan.",13,"#475569",false));r.addView(tips,lp());return s;}
    @Override public void onOrdersChanged(List<UnifiedLiveOrderCenter.Order> orders){runOnUiThread(()->{UnifiedLiveOrderCenter.Order o=UnifiedLiveOrderCenter.primary(orders);activeInfo.setText(o==null?"Tidak ada perjalanan aktif.":o.title()+" • "+o.statusLabel());});}
    private void shareActiveTrip(){UnifiedLiveOrderCenter.Order o=UnifiedLiveOrderCenter.primary(UnifiedLiveOrderCenter.snapshot());if(o==null){Toast.makeText(this,"Tidak ada perjalanan aktif untuk dibagikan",Toast.LENGTH_SHORT).show();return;}String pickup=o.raw.optString("pickup_address","-");String dest=o.raw.optString("delivery_address","-");String driver=o.raw.optString("driver_name",o.raw.optString("driver_username",o.raw.optString("driver","-")));String text="Transiva Safety Share\nLayanan: "+o.title()+"\nStatus: "+o.statusLabel()+"\nDriver: "+driver+"\nJemput: "+pickup+"\nTujuan: "+dest+"\nOrder: "+o.id;Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,text);startActivity(Intent.createChooser(i,"Bagikan perjalanan"));}
    private LinearLayout card(String a,String b,Runnable run){LinearLayout x=box();x.addView(t(a,16,"#0B3A78",true));TextView d=t(b,12,"#64748B",false);d.setPadding(0,dp(6),0,0);x.addView(d);x.setOnClickListener(v->run.run());return x;}private LinearLayout box(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(16),dp(16),dp(16),dp(16));x.setBackground(round("#FFFFFF",20));x.setElevation(dp(2));return x;}private LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(14),0,0);return p;}private TextView t(String s,int sp,String c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(Color.parseColor(c));if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable round(String c,int r){GradientDrawable g=new GradientDrawable();g.setColor(Color.parseColor(c));g.setCornerRadius(dp(r));return g;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
