package com.transiva.app;
import android.app.*;import android.os.*;import android.graphics.Color;import android.content.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;
/** Dedicated owner screen: realtime invitation status and local smooth countdown. */
public class SplitBillSessionActivity extends Activity{
 private String key="";private LinearLayout list;private TextView timer,title;private final Handler h=new Handler(Looper.getMainLooper());private Runnable clock,poll;private long deadline;private boolean loading;
 private final BroadcastReceiver rt=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(key.equals(i.getStringExtra("session_key")))load();}};
 public void onCreate(Bundle b){super.onCreate(b);key=getIntent().getStringExtra("session_key");build();registerRt();load();}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(24),dp(34),dp(24),dp(24));root.setBackgroundColor(Color.WHITE);setContentView(root);title=new TextView(this);title.setText("Split Bill • Menunggu konfirmasi");title.setTextSize(25);title.setTextColor(Color.rgb(11,58,120));title.setTypeface(null,1);root.addView(title);timer=new TextView(this);timer.setText("60 detik");timer.setGravity(Gravity.CENTER);timer.setTextSize(28);timer.setPadding(0,dp(18),0,dp(18));root.addView(timer);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));TextView hint=new TextView(this);hint.setText("Status diperbarui otomatis. Tidak perlu keluar/masuk halaman.");hint.setTextColor(Color.GRAY);root.addView(hint);}
 private void load(){if(loading)return;loading=true;new Thread(()->{try{JSONObject q=new JSONObject().put("action","status").put("session_key",key);JSONObject r=TransivaHttpRepository.postJson(this,ApiConfig.SERVER+"split_bill.php",q,12000);h.post(()->{loading=false;render(r);});}catch(Exception e){h.post(()->loading=false);}}).start();}
 private void render(JSONObject r){if(!r.optBoolean("success"))return;JSONObject s=r.optJSONObject("session");JSONArray ps=r.optJSONArray("participants");int sec=s==null?0:s.optInt("expires_in");deadline=SystemClock.elapsedRealtime()+sec*1000L;String st=s==null?"":s.optString("status");title.setText("ready".equals(st)?"Split Bill • Semua siap ✓":"Split Bill • Menunggu konfirmasi");list.removeAllViews();if(ps!=null)for(int i=0;i<ps.length();i++){JSONObject p=ps.optJSONObject(i);TextView row=new TextView(this);String x=p.optString("status");row.setText(("accepted".equals(x)?"✅ ":"declined".equals(x)?"❌ ":"⏳ ")+p.optString("username","Customer")+"  •  "+Math.round(p.optDouble("percentage"))+"%");row.setTextSize(18);row.setTextColor("accepted".equals(x)?Color.rgb(0,145,85):Color.rgb(40,50,65));row.setPadding(dp(12),dp(14),dp(12),dp(14));list.addView(row);}startClock();}
 private void startClock(){if(clock!=null)h.removeCallbacks(clock);clock=new Runnable(){public void run(){long ms=Math.max(0,deadline-SystemClock.elapsedRealtime());long sec=(ms+999)/1000;timer.setText(sec>0?"⏳ "+sec+" detik":"Waktu undangan selesai");if(ms>0)h.postDelayed(this,250);}};h.post(clock);}
 private void registerRt(){IntentFilter f=new IntentFilter("com.transiva.app.SPLIT_BILL_REALTIME");if(Build.VERSION.SDK_INT>=33)registerReceiver(rt,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(rt,f);poll=new Runnable(){public void run(){load();h.postDelayed(this,1000);}};h.postDelayed(poll,1000);}
 private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}protected void onDestroy(){if(clock!=null)h.removeCallbacks(clock);if(poll!=null)h.removeCallbacks(poll);try{unregisterReceiver(rt);}catch(Exception ignored){}super.onDestroy();}
}
