package com.transiva.app;
import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import org.json.*;
public class SplitBillInviteActivity extends Activity{
 private String key="";private LinearLayout root;private Handler h=new Handler(Looper.getMainLooper());private Runnable tick;
 public void onCreate(Bundle b){super.onCreate(b);key=getIntent().getStringExtra("session_key");root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(40,60,40,40);setContentView(root);load();}
 private void load(){new Thread(()->{try{JSONObject p=new JSONObject().put("action","status").put("session_key",key);JSONObject r=TransivaHttpRepository.postJson(this,ApiConfig.ROOT+"server/split_bill.php",p,12000);h.post(()->render(r));}catch(Exception e){h.post(()->msg("Koneksi server bermasalah"));}}).start();}
 private void render(JSONObject r){root.removeAllViews();TextView t=new TextView(this);t.setText("💳 Undangan Split Bill");t.setTextSize(25);t.setTextColor(Color.rgb(11,58,120));root.addView(t);if(!r.optBoolean("success")){msg(r.optString("message","Undangan tidak tersedia"));return;}JSONObject s=r.optJSONObject("session");int sec=s==null?0:s.optInt("expires_in");TextView info=new TextView(this);info.setText("Anda diundang membayar bersama melalui Transiva Pay.\n\nSisa waktu: "+sec+" detik\nSaldo akan dipotong hanya saat order benar-benar dibuat.");info.setTextSize(17);info.setPadding(0,30,0,30);root.addView(info);Button yes=new Button(this);yes.setText("✓ Terima Split Bill");yes.setEnabled(sec>0);yes.setOnClickListener(v->respond(true));root.addView(yes);Button no=new Button(this);no.setText("Tolak");no.setOnClickListener(v->respond(false));root.addView(no);if(sec>0){if(tick!=null)h.removeCallbacks(tick);tick=()->load();h.postDelayed(tick,2000);}}
 private void respond(boolean ok){new Thread(()->{try{JSONObject p=new JSONObject().put("action","respond").put("session_key",key).put("accept",ok);JSONObject r=TransivaHttpRepository.postJson(this,ApiConfig.ROOT+"server/split_bill.php",p,12000);h.post(()->{Toast.makeText(this,r.optString("message"),Toast.LENGTH_LONG).show();if(r.optBoolean("success"))finish();});}catch(Exception e){h.post(()->msg("Gagal memproses undangan"));}}).start();}
 private void msg(String s){TextView v=new TextView(this);v.setText(s);v.setTextSize(17);v.setPadding(0,30,0,0);root.addView(v);}protected void onDestroy(){if(tick!=null)h.removeCallbacks(tick);super.onDestroy();}
}
