package com.transiva.app;

import android.app.Activity;import android.content.Intent;import android.graphics.Color;import android.os.Bundle;import android.view.Gravity;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;

public class TransivaFamilyActivity extends Activity {
  private static final String URL="https://transiva.my.id/server/customer_family.php"; private LinearLayout list;
  @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(22),dp(18),dp(18));root.setBackgroundColor(Color.parseColor("#F6F9FE"));TextView t=txt("Transiva Family",24,true);root.addView(t);root.addView(txt("Simpan anggota keluarga lalu pesankan perjalanan atas nama mereka.",14,false));Button add=btn("+ Tambah anggota");add.setOnClickListener(v->edit(0,"","","Keluarga"));root.addView(add,new LinearLayout.LayoutParams(-1,dp(50)));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);load();}
  private void load(){run(() -> {try{JSONObject r=get(URL+"?action=list");runOnUiThread(()->render(r.optJSONArray("members")));}catch(Exception e){toast("Gagal memuat Family");}});}
  private void render(JSONArray a){list.removeAllViews();if(a==null||a.length()==0){list.addView(txt("Belum ada anggota keluarga.",14,false));return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null)continue;LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(14),dp(12),dp(14),dp(12));row.setBackgroundColor(Color.WHITE);String name=x.optString("name","Keluarga");row.addView(txt(name+" • "+x.optString("relationship","Keluarga"),16,true));row.addView(txt(x.optString("phone",""),13,false));LinearLayout act=new LinearLayout(this);Button ride=btn("Pesankan TransRide");Button edit=btn("Edit");act.addView(ride,new LinearLayout.LayoutParams(0,dp(46),1));act.addView(edit,new LinearLayout.LayoutParams(0,dp(46),1));row.addView(act);int id=x.optInt("id");ride.setOnClickListener(v->{Intent in=new Intent(this,TransRideActivity.class);in.putExtra("family_member_id",id);in.putExtra("family_member_name",name);startActivity(in);});edit.setOnClickListener(v->edit(id,name,x.optString("phone",""),x.optString("relationship","Keluarga")));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(10),0,0);list.addView(row,lp);}}
  private void edit(int id,String n,String p,String r){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText name=new EditText(this);name.setHint("Nama");name.setText(n);EditText phone=new EditText(this);phone.setHint("Nomor HP");phone.setText(p);EditText rel=new EditText(this);rel.setHint("Hubungan (Ibu/Anak/Ayah)");rel.setText(r);box.addView(name);box.addView(phone);box.addView(rel);new TransivaAlertDialogBuilder(this).setTitle(id>0?"Edit anggota":"Tambah anggota").setView(box).setNegativeButton(id>0?"Hapus":"Batal",(d,w)->{if(id>0)save(new JSONObject(),"delete",id);}).setPositiveButton("Simpan",(d,w)->{try{JSONObject o=new JSONObject();o.put("name",name.getText().toString().trim());o.put("phone",phone.getText().toString().trim());o.put("relationship",rel.getText().toString().trim());save(o,"save",id);}catch(Exception ignored){}}).show();}
  private void save(JSONObject o,String action,int id){run(()->{try{o.put("action",action);if(id>0)o.put("id",id);JSONObject r=post(URL,o);runOnUiThread(()->{toast(r.optString("message","Selesai"));if(r.optBoolean("success"))load();});}catch(Exception e){toast("Gagal menyimpan");}});}
  private JSONObject get(String u)throws Exception{HttpURLConnection c=CustomerApiClient.open(this,u);c.setRequestMethod("GET");return read(c);}private JSONObject post(String u,JSONObject o)throws Exception{HttpURLConnection c=CustomerApiClient.open(this,u);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream os=c.getOutputStream()){os.write(o.toString().getBytes(StandardCharsets.UTF_8));}return read(c);}private JSONObject read(HttpURLConnection c)throws Exception{InputStream in=(c.getResponseCode()<400?c.getInputStream():c.getErrorStream());BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String l;while((l=br.readLine())!=null)s.append(l);return new JSONObject(s.toString());}
  private void run(Runnable r){TransivaNetworkExecutor.execute(r);}private TextView txt(String s,int z,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.parseColor("#0B3A78"));if(b)v.setTypeface(null,1);v.setPadding(0,dp(6),0,dp(6));return v;}private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_SHORT).show());}
}
